from django.db import models

# Create your models here.
class Stock(models.Model):
    date = models.DateTimeField(auto_now_add= True)
    source = models.CharField(max_length = 50, verbose_name='', blank=True, null=True)
    infoSymbol = models.CharField(max_length = 10, verbose_name='', blank=True, null=True)
    infoTitle = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoMarket_fa = models.CharField(max_length = 10, verbose_name='', blank=True, null=True)
    infoFlowTitle = models.CharField(max_length = 10, verbose_name='', blank=True, null=True)
    infoLastTradePDrCotVal = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoLastTradeLastChange = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoLastTradeLastChangePercentage = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoLastPricePClosing = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoLastPriceClosingChange = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoLastPriceClosingChangePercentage = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    lastDate = models.DateTimeField(null=True, blank=True)
    tradesZTotTran = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesQTotTran5J = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesQTotCap = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcMotevasetHajmHarMoamele = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoPriceYesterday = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoPriceFirst = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoDayRangePriceMin = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoDayRangePriceMax = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    demands1_1 = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    demands1_0 = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    demands1_2 = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    demands1_4 = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    demands1_5 = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    demands1_3 = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesArzeshBazar = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcArzeshRoozDarayi = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcArzeshDaftariDarayi = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcAkharinSarmaye = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcBedehi = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcHoghoghSahebanSaham= models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcPishbiniDaramad = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    etcSoodKhalesTtm = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoPe = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoPb = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    infoPs = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesBuyAndSellBuyIVolume = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesBuyAndsellBuy_NVolume = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesBuyAndSellSellIVolume = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)
    tradesBuyAndSellSellNVolume = models.CharField(max_length = 30, verbose_name='', blank=True, null=True)